#!/bin/bash

currentPath="$( cd "$( dirname "$0"  )" && pwd  )"
cd ../../
pwdPath="$(pwd)"

# convert collection into Anserini's jsonl file
python $pwdPath/depend/anserini/tools/scripts/msmarco/convert_collection_to_jsonl.py \
        --collection-path $pwdPath/data/collections/msmarco-passage/collection.tsv \
        --output-folder $pwdPath/data/collections/msmarco-passage/collection_jsonl



# build index
sh $pwdPath/depend/anserini/target/appassembler/bin/IndexCollection \
    -threads 9 \
    -collection JsonCollection \
    -generator DefaultLuceneDocumentGenerator \
    -input $pwdPath/data/collections/msmarco-passage/collection_jsonl \
    -index $pwdPath/data/indexes/msmarco-passage/lucene-index-msmarco \
    -storePositions \
    -storeDocvectors \
    -storeRaw
